import {
  addBulletList,
  addFooter,
  addParagraph,
  addSectionHeading,
  buildPdfFilename,
  createPdfDoc,
  formatDate,
  safeText,
} from './shared';

export async function generateNDA({
  buyerName,
  supplierName,
  buyerCompanyName,
  supplierCompanyName,
  buyerAddress,
  supplierAddress,
  buyerRegistrationNumber,
  supplierRegistrationNumber,
  dealName,
  dealId,
  date,
  generatedOn,
  additionalDetails = [],
  source = {},
}) {
  const filename = buildPdfFilename('NDA', dealName);
  const { doc, state } = createPdfDoc({
    title: 'NON-DISCLOSURE AGREEMENT (NDA)',
    subtitle: 'Confidentiality template aligned to the deal request',
    documentCode: 'NDA',
    referenceLabel: 'Deal ID',
    referenceValue: dealId || dealName,
  });

  const formattedDate = safeText(date || generatedOn || formatDate(new Date()), '');
  const transactionDescription = safeText(source.transactionDescription || dealName, dealName || 'the transaction');
  const termYears = safeText(source.confidentialityTermYears || 2, '2');
  const survivalYears = safeText(source.confidentialitySurvivalYears || 3, '3');
  const governingLaw = safeText(source.governingLaw, 'JURISDICTION');

  addParagraph(doc, state, `This Non-Disclosure Agreement (“Agreement”) is entered into on ${formattedDate}, by and between:`, { size: 10.6 });
  addParagraph(doc, state, `Party A: ${buyerCompanyName || buyerName || 'Company Name'}${buyerAddress ? `, ${buyerAddress}` : ''}${buyerRegistrationNumber ? `, ${buyerRegistrationNumber}` : ''}`);
  addParagraph(doc, state, `Party B: ${supplierCompanyName || supplierName || 'Company Name'}${supplierAddress ? `, ${supplierAddress}` : ''}${supplierRegistrationNumber ? `, ${supplierRegistrationNumber}` : ''}`);
  addParagraph(doc, state, 'Collectively referred to as the “Parties”.', { size: 10.2, color: [71, 85, 105] });

  addSectionHeading(doc, state, '1. Purpose');
  addParagraph(
    doc,
    state,
    `The Parties intend to explore a potential business relationship regarding ${transactionDescription} and may exchange confidential information.`,
  );

  addSectionHeading(doc, state, '2. Definition of Confidential Information');
  addBulletList(doc, state, [
    'Commercial, financial, and technical information',
    'Trade data, pricing, suppliers, and client lists',
    'Contracts, agreements, and transaction details',
  ]);

  addSectionHeading(doc, state, '3. Obligations');
  addBulletList(doc, state, [
    'Keep all Confidential Information strictly confidential',
    'Not disclose it to third parties without prior written consent',
    'Use the information solely for the Purpose stated above',
  ]);

  addSectionHeading(doc, state, '4. Exclusions');
  addBulletList(doc, state, [
    'Is publicly available',
    'Was already known prior to disclosure',
    'Is required to be disclosed by law',
  ]);

  addSectionHeading(doc, state, '5. Non-Circumvention');
  addParagraph(doc, state, 'The Parties agree not to bypass or circumvent each other in any transaction introduced during the term of this Agreement.');

  addSectionHeading(doc, state, '6. Term');
  addParagraph(doc, state, `This Agreement remains valid for a period of ${termYears} years, and confidentiality obligations survive for ${survivalYears} years after termination.`);

  if (additionalDetails.length > 0) {
    addSectionHeading(doc, state, 'Additional Deal Information');
    addBulletList(doc, state, additionalDetails.map((item) => `${item.label}: ${item.value}`));
  }

  addSectionHeading(doc, state, '7. Governing Law');
  addParagraph(doc, state, `This Agreement shall be governed by the laws of ${governingLaw}.`);

  addSectionHeading(doc, state, '8. Miscellaneous');
  addParagraph(doc, state, 'This Agreement does not create any partnership or obligation to proceed with a transaction.');

  addSectionHeading(doc, state, '9. Signatures');
  addParagraph(doc, state, 'Party A: ___________________');
  addParagraph(doc, state, 'Name:');
  addParagraph(doc, state, 'Title:');
  addParagraph(doc, state, 'Party B: ___________________');
  addParagraph(doc, state, 'Name:');
  addParagraph(doc, state, 'Title:');

  addSectionHeading(doc, state, 'Disclaimer');
  addParagraph(doc, state, 'This document is a general template and does not constitute legal advice. Users are advised to seek professional legal review before use.');

  addFooter(doc, state, 'Non-Disclosure Agreement generated by Tradafy');
  const blob = doc.output('blob');
  doc.save(filename);
  return { doc, blob, filename };
}
