import {
  addBulletList,
  addFooter,
  addParagraph,
  addSectionHeading,
  buildPdfFilename,
  createPdfDoc,
  formatCurrency,
  formatDate,
  safeText,
} from './shared';

export async function generateLOI({
  buyerName,
  supplierName,
  buyerCompanyName,
  supplierCompanyName,
  buyerAddress,
  supplierAddress,
  dealName,
  quantity,
  price,
  currency = 'USD',
  dealId,
  date,
  generatedOn,
  additionalDetails = [],
  source = {},
}) {
  const filename = buildPdfFilename('LOI', dealName);
  const { doc, state } = createPdfDoc({
    title: 'LETTER OF INTENT (LOI)',
    subtitle: 'Commercial template aligned to the deal request',
    documentCode: 'LOI',
    referenceLabel: 'Deal ID',
    referenceValue: dealId || dealName,
  });

  const formattedDate = safeText(date || generatedOn || formatDate(new Date()), '');
  const formattedPrice = price === '' || price == null ? '—' : formatCurrency(price, currency);
  const formattedValidity = safeText(source.validityDays || source.validity || source.validUntil, 'X days');
  const formattedPayment = safeText(source.paymentTerms, 'Letter of Credit (LC) / SBLC / TT / other');
  const formattedInspection = safeText(source.inspectionBy, 'SGS / Bureau Veritas / other agreed party');
  const formattedIncoterm = safeText(source.incoterm, 'FOB / CIF / etc.');
  const formattedDelivery = safeText(source.deliveryLocation || source.deliveryTimeline || source.destinationCountry, 'Port / location');

  addParagraph(doc, state, `Date: ${formattedDate}`, { size: 10.2, color: [71, 85, 105] });
  addParagraph(
    doc,
    state,
    `From / Buyer: ${buyerName || 'Buyer'}${buyerCompanyName ? ` (${buyerCompanyName})` : ''}${buyerAddress ? `, ${buyerAddress}` : ''}`,
    { size: 10.4, color: [71, 85, 105] }
  );
  addParagraph(
    doc,
    state,
    `To / Counterparty: ${supplierName || 'Counterparty'}${supplierCompanyName ? ` (${supplierCompanyName})` : ''}${supplierAddress ? `, ${supplierAddress}` : ''}`,
    { size: 10.4, color: [71, 85, 105] }
  );
  addParagraph(
    doc,
    state,
    `Buyer name: ${buyerName || '—'} | Counterparty name: ${supplierName || '—'}`,
    { size: 10.2, color: [71, 85, 105] }
  );

  addSectionHeading(doc, state, '1. Subject');
  addParagraph(
    doc,
    state,
    `This Letter of Intent outlines the intention to enter into a transaction for the purchase of ${dealName || 'the product'}.\nProduct: ${dealName || '—'}\nQuantity: ${safeText(quantity, '—')}\nPrice: ${formattedPrice}\nIncoterms: ${formattedIncoterm}\nDelivery: ${formattedDelivery}`,
  );

  addSectionHeading(doc, state, '2. Payment Terms');
  addParagraph(doc, state, `Payment shall be made via: ${formattedPayment}.`);

  addSectionHeading(doc, state, '3. Inspection');
  addParagraph(doc, state, `Goods shall be subject to inspection by: ${formattedInspection}.`);

  addSectionHeading(doc, state, '4. Validity');
  addParagraph(doc, state, `This LOI is valid for ${formattedValidity} from the date of issuance.`);

  addSectionHeading(doc, state, '5. Non-Binding Nature');
  addParagraph(
    doc,
    state,
    'This LOI is non-binding and intended solely as an expression of interest, except for confidentiality and exclusivity (if applicable).',
  );

  addSectionHeading(doc, state, '6. Next Steps');
  addBulletList(doc, state, [
    'Drafting of a Sale & Purchase Agreement (SPA)',
    'Exchange of corporate documents',
    'Finalization of payment instrument',
  ]);

  if (additionalDetails.length > 0) {
    addSectionHeading(doc, state, 'Additional Deal Information');
    addBulletList(
      doc,
      state,
      additionalDetails.map((item) => `${item.label}: ${item.value}`),
    );
  }

  addSectionHeading(doc, state, '7. Governing Law');
  addParagraph(doc, state, `Governing law: ${safeText(source.governingLaw, 'To be defined in the final contract.')}.`);

  addSectionHeading(doc, state, '8. Signature');
  addParagraph(doc, state, 'Buyer: ___________________');
  addParagraph(doc, state, 'Name:');
  addParagraph(doc, state, 'Title:');

  addSectionHeading(doc, state, 'Disclaimer');
  addParagraph(doc, state, 'This document is a general template and does not constitute legal advice.');

  addFooter(doc, state, 'Letter of Intent generated by Tradafy');
  const blob = doc.output('blob');
  doc.save(filename);
  return { doc, blob, filename };
}
